### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Mitron57** [linksplatform/Data.Doublets#357]
If you launch this code, you get SIGSEGV

    fn test() {

        let file = std::fs::File::options()
            .create(true)
            .write(true)
            .read(true)
            .open("db.links")
            .unwrap();
        let storage = FileMappedMem::new(file).unwrap();
        let mut links = unit::Store::<usize, _>::new(storage).unwrap();
        for _ in 0..1_000_000 {
            links.create_point().unwrap();
        }
        links.delete_all().unwrap();
    }

**Comment by uselessgoddess** [comment]
I checked it. `.delete_all()` has no effect. 
Please try use my new commit from `mem` repository
```toml
[dependencies]
mem = { git = "https://github.com/linksplatform/Memory", package = "platform-mem" }
```
